// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using multi_tenant_beauty_platform_back.Infrastructure.Data;

#nullable disable

namespace multi_tenant_beauty_platform_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522075201_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.OnboardingSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("NotificationsAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("OnboardingSubmissions");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.SalonProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("text");

                    b.Property<string>("PreferredColors")
                        .HasColumnType("text");

                    b.Property<string>("SalonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SocialMedias")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SalonProfiles");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.ServiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SpecialistProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistProfileId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("ServiceItems");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.SpecialistProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PreferredColors")
                        .HasColumnType("text");

                    b.Property<string>("SocialMedias")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SpecialistProfiles");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GraphicsUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("SalonProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SalonProfileId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.SalonProfile", b =>
                {
                    b.HasOne("multi_tenant_beauty_platform_back.Domain.Entities.User", null)
                        .WithOne("SalonProfile")
                        .HasForeignKey("multi_tenant_beauty_platform_back.Domain.Entities.SalonProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.ServiceItem", b =>
                {
                    b.HasOne("multi_tenant_beauty_platform_back.Domain.Entities.SpecialistProfile", null)
                        .WithMany("Services")
                        .HasForeignKey("SpecialistProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("multi_tenant_beauty_platform_back.Domain.Entities.StaffMember", null)
                        .WithMany("Services")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.SpecialistProfile", b =>
                {
                    b.HasOne("multi_tenant_beauty_platform_back.Domain.Entities.User", null)
                        .WithOne("SpecialistProfile")
                        .HasForeignKey("multi_tenant_beauty_platform_back.Domain.Entities.SpecialistProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.StaffMember", b =>
                {
                    b.HasOne("multi_tenant_beauty_platform_back.Domain.Entities.SalonProfile", null)
                        .WithMany("StaffMembers")
                        .HasForeignKey("SalonProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.SalonProfile", b =>
                {
                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.SpecialistProfile", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.StaffMember", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("multi_tenant_beauty_platform_back.Domain.Entities.User", b =>
                {
                    b.Navigation("SalonProfile");

                    b.Navigation("SpecialistProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
